- name: add test cronjob
  hosts: all
  tasks:
    - name: test cronjob
      become: true
      cron:
        name: test cronjob
        state: present
        minute: '*/5'
        job: "/home/pelikohdenaytto/script.sh"