- name: upgrade distro
  hosts: all
  tasks:
    - name: Update package repository
      become: true
      shell: sed -i 's/jessie/stretch/g' /etc/apt/sources.list

    - name: Update all packages and distro to the latest version
      become: true
      apt:
        update_cache: yes
        upgrade: full