- name: Setup Ansible Pull
  hosts: all
  become: True

  vars:
    ansiblepull_playbook: "{{ ansiblepull_workdir }}/playbooks/pull.yml"
    ansiblepull_repo: "git@gitlab.acme.com/internal.git"
    ansiblepull_known_hosts:
      - name: "gitlab.acme.com"
        state: present
        key: "gitlab.acme.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCEPm0nPQBk+W4FBWSuI2wP0vO2W5cfDQV3B65WayiQPCh5kQIaTfDaRXIHACu9GcZRx5mhTsXYt+jY2egvLwazX5xvvQqDZX7wLw+qJXnpb1pqS7koINnAopGspp5v/+KPk7e3SRbLdNDk8O/g7uXb1PwaryebQM2+eluDebh1zbDd2QgKHf1/p4gZ66m4QJ9s17+Qzj3AJO+5fNr9z0MxPkYkf3jLvJ8PmAqGT+6AYlAh889yCrrC+yGj7VH/H6P3dEakj2xEx3Ib4g42EjKOpumoCVLY6dKrtSlkyOVBEOkf7G3liIV2ZNm6smWsJsnCTMPy4o9ioxF+x5GG1nsL"

  roles:
    - samdoran.repo-epel
    - ansible-pull