- name: replace content in file
  hosts: all
  tasks:

    - name: Remove access from remote sources through Docker socket
      #when: env == "prod" or env == "stg"
      replace:
        path: content/docker.service
        regexp: '-H tcp://0.0.0.0:2375'
        replace: ''
        backup: yes
